os: linux

language: minimal

dist: jammy

services:
  - docker

env:
  - BUILD_TYPE=focal-ros1
  - BUILD_TYPE=jammy-ros2
  - BUILD_TYPE=noble-ros2

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/  # version tags

notifications:
  email:
    recipients:
      - arturo.laurenzi@iit.it
    on_success: never
    on_failure: always

before_script:
  - cd docker/$BUILD_TYPE
  - docker compose up -d

script: 
  - set -e
  - docker compose exec dev scripts/build.bash 
  - docker compose exec dev scripts/test.bash 
  - docker compose down || true
  - set +e
